version: "3.9"

services:
  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 1337:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
    expose:
      - 5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
      IS_WORKER: true
      GOOGLE_BUCKET: ${GOOGLE_BUCKET}
    command: flask run
    networks:
      - default
