version: "3.9"

services:
  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 1337:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
    expose:
      - 5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
      GOOGLE_ACCESS_FILE: ${GOOGLE_ACCESS_FILE}
      GOOGLE_BUCKET: ${GOOGLE_BUCKET}
    depends_on:
      - redis
    networks:
      - default

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - default