version: "3.9"

services:

  app:
    build:
      context: .
    ports:
      - ${PORT}
    environment:
      DATABASE_URI: ${DATABASE_URI}
      IS_WORKER: 'true'
      PORT: ${PORT}
      GOOGLE_BUCKET: ${GOOGLE_BUCKET}
    #command: gunicorn --conf ./gunicorn.conf.py app:app --bind 0.0.0.0:${PORT}
    networks:
      - default
