version: "3.9"

services:
  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 1337:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - type: bind
        source: ${HOST_PATH}
        target: /app/files/static
    depends_on:
      - web

  web:
    build:
      context: .
    expose:
      - 5000
    volumes:
      - type: bind
        source: ${HOST_PATH}
        target: /app/files/static
    environment:
      DATABASE_URI: ${DATABASE_URI}
    depends_on:
      - redis
    networks:
      - default

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - default