version: "3.9"

services:
  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 1337:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/files/static
    depends_on:
      - web

  web:
    build:
      context: .
    expose:
      - 5000
    volumes:
      - static_volume:/app/files/static
    environment:
      DATABASE_URI: "postgresql://admin:admin@db:5432/tool"
    depends_on:
      - db
      - redis
    links:
      - db
    networks:
      - default

  celery:
    build:
      context: .
    volumes:
      - static_volume:/app/files/static
    environment:
      DATABASE_URI: "postgresql://admin:admin@db:5432/tool"
    depends_on:
      - redis
      - web
    command: celery -A app.celery worker --loglevel=info
    networks:
      - default

  db:
    image: postgres
    environment:
      - POSTGRES_DB=tool
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    networks:
      - default

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - default

volumes:
  static_volume:
