version: "3.9"

services:
  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 1337:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/files/static
      - media_volume:/files/media
    depends_on:
      - web

  web:
    build: .
    expose:
      - 5000
    volumes:
      - .:/app
    environment:
      DATABASE_URI: "postgresql://admin:admin@db:5432/tool"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - db
      - redis
    links:
      - db
    networks:
      - default

  db:
    image: postgres
    environment:
      - POSTGRES_DB=tool
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    networks:
      - default

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - default

volumes:
  static_volume:
  media_volume:
