version: "3.9"

services:

  worker:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
      IS_WORKER: 'true'
      GOOGLE_BUCKET: ${GOOGLE_BUCKET}
    command: flask run
    networks:
      - default
